/**
 * Constantes relacionadas con los estados de aplicaciones
 * Centraliza todos los valores de estados posibles y campos relacionados
 */

export const APPLICATION_STATES = {
  // Estados globales
  NEW: 'new',
  IN_REVIEW: 'in_review',
  APPROVED: 'approved',
  REJECTED: 'rejected',
  POR_DISPERSAR: 'por_dispersar',
  COMPLETED: 'completed',
  CANCELLED: 'cancelled',
  EXPIRED: 'expired',
  
  // Campos de estado específicos
  STATUS_FIELDS: {
    GLOBAL: 'status',
    ADVISOR: 'advisor_status',
    COMPANY: 'company_status'
  },
  
  // Entidades que pueden actualizar estados
  ENTITIES: {
    ADVISOR: 'ADVISOR',
    COMPANY: 'COMPANY',
    SYSTEM: 'SYSTEM'
  },
  
  // Estado de aprobaciones
  APPROVAL: {
    PENDING: 'pending',
    APPROVED: 'approved',
    REJECTED: 'rejected'
  }
};

/**
 * Mapa de transiciones válidas entre estados
 * Define qué transiciones son permitidas para cada rol
 */
export const VALID_STATUS_TRANSITIONS = {
  // Transiciones permitidas para asesores
  ADVISOR: {
    [APPLICATION_STATES.NEW]: [APPLICATION_STATES.IN_REVIEW, APPLICATION_STATES.APPROVED, APPLICATION_STATES.REJECTED],
    [APPLICATION_STATES.IN_REVIEW]: [APPLICATION_STATES.NEW, APPLICATION_STATES.APPROVED, APPLICATION_STATES.REJECTED],
    [APPLICATION_STATES.APPROVED]: [APPLICATION_STATES.IN_REVIEW, APPLICATION_STATES.REJECTED],
    [APPLICATION_STATES.REJECTED]: [APPLICATION_STATES.NEW, APPLICATION_STATES.IN_REVIEW, APPLICATION_STATES.APPROVED],
    [APPLICATION_STATES.POR_DISPERSAR]: [APPLICATION_STATES.COMPLETED],
    [APPLICATION_STATES.COMPLETED]: []
  },
  
  // Transiciones permitidas para empresas
  COMPANY: {
    [APPLICATION_STATES.NEW]: [APPLICATION_STATES.IN_REVIEW, APPLICATION_STATES.APPROVED, APPLICATION_STATES.REJECTED],
    [APPLICATION_STATES.IN_REVIEW]: [APPLICATION_STATES.NEW, APPLICATION_STATES.APPROVED, APPLICATION_STATES.REJECTED],
    [APPLICATION_STATES.APPROVED]: [APPLICATION_STATES.IN_REVIEW, APPLICATION_STATES.REJECTED],
    [APPLICATION_STATES.REJECTED]: [APPLICATION_STATES.NEW, APPLICATION_STATES.IN_REVIEW, APPLICATION_STATES.APPROVED],
    [APPLICATION_STATES.POR_DISPERSAR]: [],
    [APPLICATION_STATES.COMPLETED]: []
  },
  
  // Transiciones permitidas para administradores
  ADMIN: {
    [APPLICATION_STATES.NEW]: [APPLICATION_STATES.IN_REVIEW, APPLICATION_STATES.APPROVED, APPLICATION_STATES.REJECTED, APPLICATION_STATES.CANCELLED],
    [APPLICATION_STATES.IN_REVIEW]: [APPLICATION_STATES.NEW, APPLICATION_STATES.APPROVED, APPLICATION_STATES.REJECTED, APPLICATION_STATES.CANCELLED],
    [APPLICATION_STATES.APPROVED]: [APPLICATION_STATES.NEW, APPLICATION_STATES.IN_REVIEW, APPLICATION_STATES.REJECTED, APPLICATION_STATES.POR_DISPERSAR, APPLICATION_STATES.CANCELLED],
    [APPLICATION_STATES.REJECTED]: [APPLICATION_STATES.NEW, APPLICATION_STATES.IN_REVIEW, APPLICATION_STATES.APPROVED, APPLICATION_STATES.CANCELLED],
    [APPLICATION_STATES.POR_DISPERSAR]: [APPLICATION_STATES.APPROVED, APPLICATION_STATES.COMPLETED, APPLICATION_STATES.CANCELLED],
    [APPLICATION_STATES.COMPLETED]: [APPLICATION_STATES.POR_DISPERSAR, APPLICATION_STATES.CANCELLED]
  }
};

/**
 * Reglas de aprobación automática
 * Define cuándo se pasa automáticamente a POR_DISPERSAR
 */
export const AUTO_APPROVAL_RULES = {
  BOTH_APPROVED: {
    condition: (advisorStatus: string, companyStatus: string) => 
      advisorStatus === APPLICATION_STATES.APPROVED && companyStatus === APPLICATION_STATES.APPROVED,
    nextStatus: APPLICATION_STATES.POR_DISPERSAR
  }
};

/**
 * Etiquetas para mostrar los estados en la interfaz
 */
export const STATUS_LABELS = {
  [APPLICATION_STATES.NEW]: 'Nueva',
  [APPLICATION_STATES.IN_REVIEW]: 'En Revisión',
  [APPLICATION_STATES.APPROVED]: 'Aprobada',
  [APPLICATION_STATES.REJECTED]: 'Rechazada',
  [APPLICATION_STATES.POR_DISPERSAR]: 'Por Dispersar',
  [APPLICATION_STATES.COMPLETED]: 'Completada',
  [APPLICATION_STATES.CANCELLED]: 'Cancelada',
  [APPLICATION_STATES.EXPIRED]: 'Expirada'
};

/**
 * Colores asociados con cada estado para UI
 */
export const STATUS_COLORS = {
  [APPLICATION_STATES.NEW]: 'blue',
  [APPLICATION_STATES.IN_REVIEW]: 'orange',
  [APPLICATION_STATES.APPROVED]: 'green',
  [APPLICATION_STATES.REJECTED]: 'red',
  [APPLICATION_STATES.POR_DISPERSAR]: 'purple',
  [APPLICATION_STATES.COMPLETED]: 'teal',
  [APPLICATION_STATES.CANCELLED]: 'gray',
  [APPLICATION_STATES.EXPIRED]: 'darkgray'
}; 