export enum APPLICATION_TYPE {
  AUTO_LOAN = 'AUTO_LOAN',
  CAR_BACKED_LOAN = 'CAR_BACKED_LOAN',
  PERSONAL_LOAN = 'PERSONAL_LOAN',
  CASH_ADVANCE = 'CASH_ADVANCE',
}

export const APPLICATION_TYPE_LABELS = {
  [APPLICATION_TYPE.AUTO_LOAN]: 'Crédito Automotriz',
  [APPLICATION_TYPE.CAR_BACKED_LOAN]: 'Crédito con Garantía Automotriz',
  [APPLICATION_TYPE.PERSONAL_LOAN]: 'Préstamo Personal',
  [APPLICATION_TYPE.CASH_ADVANCE]: 'Adelanto de Efectivo',
}; 